import type { Activity, Organizer, Category } from './types'

export const organizers: Organizer[] = [
  {
    id: 'org-001',
    name: 'Atelier des Petits Créateurs',
    logo: 'https://picsum.photos/seed/org-001/80/80',
    rating: 4.9,
    reviewCount: 312,
    activitiesCount: 8,
    verified: true,
    description: 'Studio d\'art pour enfants au cœur de Genève. Aquarelle, sculpture, collage — chaque atelier est une aventure créative.',
  },
  {
    id: 'org-002',
    name: 'Club Sportif Junior',
    logo: 'https://picsum.photos/seed/org-002/80/80',
    rating: 4.8,
    reviewCount: 524,
    activitiesCount: 14,
    verified: true,
    description: 'Initiations sportives multidisciplinaires pour les enfants de 4 à 14 ans. Foot, tennis, natation, judo.',
  },
  {
    id: 'org-003',
    name: 'École de Musique Harmonia',
    logo: 'https://picsum.photos/seed/org-003/80/80',
    rating: 4.9,
    reviewCount: 189,
    activitiesCount: 6,
    verified: true,
    description: 'École de musique certifiée avec des professeurs diplômés. Piano, guitare, éveil musical, chant.',
  },
  {
    id: 'org-004',
    name: 'Danse Studio Lausanne',
    logo: 'https://picsum.photos/seed/org-004/80/80',
    rating: 4.7,
    reviewCount: 276,
    activitiesCount: 9,
    verified: true,
    description: 'Studio de danse contemporaine, classique et hip-hop pour enfants dès 3 ans.',
  },
  {
    id: 'org-005',
    name: 'Explorateurs en Herbe',
    logo: 'https://picsum.photos/seed/org-005/80/80',
    rating: 4.8,
    reviewCount: 143,
    activitiesCount: 5,
    verified: true,
    description: 'Ateliers scientifiques ludiques pour éveiller la curiosité des enfants de 6 à 12 ans.',
  },
  {
    id: 'org-006',
    name: 'Nature & Aventure',
    logo: 'https://picsum.photos/seed/org-006/80/80',
    rating: 4.9,
    reviewCount: 98,
    activitiesCount: 7,
    verified: true,
    description: 'Sorties nature et ateliers en plein air pour reconnecter les enfants avec leur environnement.',
  },
]

export const activities: Activity[] = [
  {
    id: 'act-001',
    slug: 'atelier-peinture-aquarelle-geneve',
    name: 'Atelier Aquarelle & Imagination',
    category: 'Art créatif',
    ageMin: 5,
    ageMax: 10,
    ageLabel: '5-7 ans',
    city: 'Genève',
    district: 'Eaux-Vives',
    npa: '1207',
    canton: 'GE',
    lat: 46.2017,
    lng: 6.1600,
    price: 28,
    priceLabel: '28 CHF / séance',
    rating: 4.9,
    reviewCount: 87,
    image: 'https://picsum.photos/seed/act-001/800/600',
    shortDescription: 'Découvrez l\'aquarelle dans un atelier convivial au cœur de Genève.',
    description: 'Plongez dans l\'univers coloré de l\'aquarelle avec notre atelier encadré par des artistes professionnels. Les enfants explorent librement les mélanges de couleurs, les textures et leur propre imaginaire à travers des projets thématiques changeant chaque semaine.',
    tags: ['Créatif', 'Peinture', 'Expression', 'Petit groupe'],
    nextDate: '2025-04-19',
    duration: '1h30',
    organizer: organizers[0],
    isIndoor: true,
    isFeatured: true,
    isPopular: true,
    isCoupDeCoeur: true,
    availableSlots: 4,
    benefits: ['Développe la créativité', 'Améliore la concentration', 'Expression émotionnelle', 'Groupe de 8 enfants max'],
    practical: {
      address: '12 rue des Eaux-Vives, 1207 Genève',
      transport: 'Bus 2, arrêt Eaux-Vives',
      equipment: 'Tout le matériel est fourni',
      toProvide: 'Un tablier ou de vieux vêtements',
    },
  },
  {
    id: 'act-002',
    slug: 'initiation-tennis-lausanne',
    name: 'Initiation Tennis — Les Petits Champions',
    category: 'Sport',
    ageMin: 4,
    ageMax: 8,
    ageLabel: '5-7 ans',
    city: 'Lausanne',
    district: 'Ouchy',
    npa: '1007',
    canton: 'VD',
    lat: 46.5080,
    lng: 6.6280,
    price: 35,
    priceLabel: '35 CHF / séance',
    rating: 4.8,
    reviewCount: 124,
    image: 'https://picsum.photos/seed/act-002/800/600',
    shortDescription: 'Initiez vos enfants au tennis dans une ambiance ludique et bienveillante.',
    description: 'Notre programme d\'initiation tennis est conçu spécialement pour les tout-petits. Avec des raquettes adaptées et des balles mousse, les enfants apprennent les bases du jeu à travers des exercices ludiques. Encadrés par des moniteurs diplômés, ils progressent à leur rythme.',
    tags: ['Sport', 'Plein air', 'Technique', 'Progression'],
    nextDate: '2025-04-20',
    duration: '1h',
    organizer: organizers[1],
    isIndoor: false,
    isFeatured: false,
    isPopular: true,
    isCoupDeCoeur: false,
    availableSlots: 6,
    benefits: ['Coordination motrice', 'Esprit sportif', 'Confiance en soi', 'Plein air'],
    practical: {
      address: 'Courts de tennis, avenue de Rhodanie, 1007 Lausanne',
      transport: 'M2, arrêt Ouchy-Olympique',
      equipment: 'Raquettes et balles fournies',
      toProvide: 'Tenue de sport et chaussures de tennis',
    },
  },
  {
    id: 'act-003',
    slug: 'eveil-musical-fribourg',
    name: 'Éveil Musical — Mes Premières Notes',
    category: 'Musique',
    ageMin: 2,
    ageMax: 5,
    ageLabel: '2-4 ans',
    city: 'Fribourg',
    district: 'Bourg',
    npa: '1700',
    canton: 'FR',
    lat: 46.8065,
    lng: 7.1620,
    price: 22,
    priceLabel: '22 CHF / séance',
    rating: 4.9,
    reviewCount: 56,
    image: 'https://picsum.photos/seed/act-003/800/600',
    shortDescription: 'Un premier contact doux et joyeux avec la musique pour les tout-petits.',
    description: 'L\'éveil musical est le meilleur cadeau que vous puissiez offrir à votre tout-petit. À travers des chansons, des instruments à percussion, des comptines et des mouvements corporels, votre enfant développe son oreille musicale tout en s\'amusant. Les parents sont invités à participer.',
    tags: ['Éveil', 'Musique', 'Parents bienvenus', 'Tout-petits'],
    nextDate: '2025-04-18',
    duration: '45min',
    organizer: organizers[2],
    isIndoor: true,
    isFeatured: true,
    isPopular: false,
    isCoupDeCoeur: true,
    availableSlots: 8,
    benefits: ['Développe l\'oreille musicale', 'Coordination corps-esprit', 'Socialisation', 'Lien parent-enfant'],
    practical: {
      address: '4 rue de Lausanne, 1700 Fribourg',
      transport: 'Bus 1, arrêt Tilleul',
      equipment: 'Instruments fournis',
      toProvide: 'Rien de particulier',
    },
  },
  {
    id: 'act-004',
    slug: 'danse-hip-hop-neuchatel',
    name: 'Hip-Hop Juniors — Énergie & Groove',
    category: 'Danse',
    ageMin: 7,
    ageMax: 12,
    ageLabel: '8-10 ans',
    city: 'Neuchâtel',
    district: 'Centre',
    npa: '2000',
    canton: 'NE',
    lat: 46.9920,
    lng: 6.9310,
    price: 30,
    priceLabel: '30 CHF / séance',
    rating: 4.7,
    reviewCount: 93,
    image: 'https://picsum.photos/seed/act-004/800/600',
    shortDescription: 'Apprenez les fondamentaux du hip-hop dans une ambiance dynamique et festive.',
    description: 'Le hip-hop junior, c\'est de l\'énergie, de la créativité et beaucoup de fun. Nos cours sont adaptés aux enfants de 7 à 12 ans, avec un apprentissage progressif des styles street dance, popping et breaking. Nos professeurs créent une atmosphère inclusive où chaque enfant peut s\'exprimer librement.',
    tags: ['Danse', 'Hip-hop', 'Énergie', 'Expression'],
    nextDate: '2025-04-23',
    duration: '1h15',
    organizer: organizers[3],
    isIndoor: true,
    isFeatured: false,
    isPopular: true,
    isCoupDeCoeur: false,
    availableSlots: 3,
    benefits: ['Rythme & coordination', 'Confiance en soi', 'Expression corporelle', 'Esprit d\'équipe'],
    practical: {
      address: '6 rue du Seyon, 2000 Neuchâtel',
      transport: 'Bus 107, arrêt Place Pury',
      equipment: 'Studio équipé',
      toProvide: 'Tenue souple et baskets propres',
    },
  },
  {
    id: 'act-005',
    slug: 'atelier-science-sion',
    name: 'Lab Juniors — Science & Découvertes',
    category: 'Science',
    ageMin: 6,
    ageMax: 11,
    ageLabel: '5-7 ans',
    city: 'Sion',
    district: 'Centre-ville',
    npa: '1950',
    canton: 'VS',
    lat: 46.2330,
    lng: 7.3600,
    price: 32,
    priceLabel: '32 CHF / séance',
    rating: 4.8,
    reviewCount: 68,
    image: 'https://picsum.photos/seed/act-005/800/600',
    shortDescription: 'Des expériences scientifiques spectaculaires pour les petits curieux.',
    description: 'Dans notre laboratoire junior, les enfants deviennent de vrais scientifiques en herbe. Chaque séance explore un thème différent : chimie des couleurs, volcans de bicarbonate, circuits électriques simples, dissection de fleurs... Tout est conçu pour allier sécurité absolue et émerveillement garanti.',
    tags: ['Science', 'Expériences', 'Curiosité', 'STEM'],
    nextDate: '2025-04-19',
    duration: '1h30',
    organizer: organizers[4],
    isIndoor: true,
    isFeatured: false,
    isPopular: false,
    isCoupDeCoeur: true,
    availableSlots: 10,
    benefits: ['Curiosité scientifique', 'Raisonnement logique', 'Expérimentation', 'Culture générale'],
    practical: {
      address: '10 avenue de la Gare, 1950 Sion',
      transport: 'Bus 1, arrêt Gare de Sion',
      equipment: 'Matériel de laboratoire fourni',
      toProvide: 'Blouse fournie sur place',
    },
  },
  {
    id: 'act-006',
    slug: 'sortie-nature-montreux',
    name: 'Explorateurs de Nature — Forêt & Animaux',
    category: 'Nature',
    ageMin: 4,
    ageMax: 10,
    ageLabel: '5-7 ans',
    city: 'Montreux',
    district: 'Quais',
    npa: '1820',
    canton: 'VD',
    lat: 46.4312,
    lng: 6.9107,
    price: 18,
    priceLabel: '18 CHF / enfant',
    rating: 4.9,
    reviewCount: 47,
    image: 'https://picsum.photos/seed/act-006/800/600',
    shortDescription: 'Partez à la découverte de la nature avec un naturaliste passionné.',
    description: 'Accompagnés d\'un naturaliste diplômé, les enfants partent à la découverte des secrets de la faune et de la flore locale. Observation d\'oiseaux, identification de plantes, construction de cabanes, traces d\'animaux... Chaque sortie est une aventure unique qui développe le sens de l\'observation et l\'amour de la nature.',
    tags: ['Nature', 'Plein air', 'Animaux', 'Randonnée'],
    nextDate: '2025-04-21',
    duration: '2h',
    organizer: organizers[5],
    isIndoor: false,
    isFeatured: true,
    isPopular: false,
    isCoupDeCoeur: false,
    availableSlots: 12,
    benefits: ['Connexion à la nature', 'Observation & curiosité', 'Exercice physique', 'Émerveillement'],
    practical: {
      address: 'Quai de la Rouvenaz, 1820 Montreux (point de RDV communiqué)',
      transport: 'Bus 201, arrêt Montreux-Marché',
      equipment: 'Carnets d\'observation fournis',
      toProvide: 'Chaussures fermées, vêtements adaptés à la météo',
    },
  },
  {
    id: 'act-007',
    slug: 'atelier-anniversaire-geneve',
    name: 'Anniversaire Magique — Atelier Créatif',
    category: 'Anniversaires',
    ageMin: 4,
    ageMax: 12,
    ageLabel: 'Tous âges',
    city: 'Genève',
    district: 'Vieille-Ville',
    npa: '1204',
    canton: 'GE',
    lat: 46.2000,
    lng: 6.1480,
    price: 45,
    priceLabel: 'À partir de 45 CHF / enfant',
    rating: 4.8,
    reviewCount: 134,
    image: 'https://picsum.photos/seed/act-007/800/600',
    shortDescription: 'Organisez un anniversaire inoubliable dans un cadre créatif et féerique.',
    description: 'Offrez à votre enfant un anniversaire dont il se souviendra toute sa vie. Nous prenons en charge tout l\'animation : atelier thématique, décoration, goûter inclus. Chaque enfant repart avec sa création personnalisée. Groupes de 8 à 20 enfants. Thèmes disponibles : licorne, dinosaure, super-héros, sorcier, explorateur.',
    tags: ['Anniversaire', 'Fête', 'Créatif', 'Sur mesure'],
    nextDate: '2025-04-26',
    duration: '2h',
    organizer: organizers[0],
    isIndoor: true,
    isFeatured: false,
    isPopular: true,
    isCoupDeCoeur: false,
    availableSlots: 20,
    benefits: ['Souvenir inoubliable', 'Tout inclus', 'Animation professionnelle', 'Cadeau personnalisé'],
    practical: {
      address: '8 Grand-Rue, 1204 Genève',
      transport: 'Bus 36, arrêt Hôtel-de-Ville',
      equipment: 'Tout inclus',
      toProvide: 'La liste des invités 48h avant',
    },
  },
  {
    id: 'act-008',
    slug: 'stage-vacances-sport-lausanne',
    name: 'Stage Vacances Multi-Sports',
    category: 'Stages vacances',
    ageMin: 6,
    ageMax: 14,
    ageLabel: '8-10 ans',
    city: 'Lausanne',
    district: 'Vidy',
    npa: '1007',
    canton: 'VD',
    lat: 46.5180,
    lng: 6.5950,
    price: 180,
    priceLabel: '180 CHF / semaine',
    rating: 4.7,
    reviewCount: 89,
    image: 'https://picsum.photos/seed/act-008/800/600',
    shortDescription: 'Une semaine de sport intense et de découvertes pour les vacances scolaires.',
    description: 'Notre stage multi-sports est la formule idéale pour les vacances scolaires. Chaque jour, un sport différent : foot, basket, tennis, natation, escalade... Les enfants sont encadrés par des éducateurs sportifs diplômés dans une ambiance conviviale et sécurisée. Accueil dès 8h, activités de 9h à 17h.',
    tags: ['Stage', 'Multi-sports', 'Vacances', 'Journée complète'],
    nextDate: '2025-04-28',
    duration: '5 jours (9h-17h)',
    organizer: organizers[1],
    isIndoor: false,
    isFeatured: true,
    isPopular: true,
    isCoupDeCoeur: true,
    availableSlots: 7,
    benefits: ['Multi-disciplines', 'Journée complète', 'Encadrement diplômé', 'Repas inclus'],
    practical: {
      address: 'Centre sportif de Vidy, 1007 Lausanne',
      transport: 'M2, arrêt UNIL-Mouline',
      equipment: 'Fourni selon les sports',
      toProvide: 'Pique-nique ou repas payant sur place (8 CHF)',
    },
  },
  {
    id: 'act-009',
    slug: 'cours-piano-fribourg',
    name: 'Piano Débutant — Mon Premier Récital',
    category: 'Musique',
    ageMin: 6,
    ageMax: 14,
    ageLabel: '5-7 ans',
    city: 'Fribourg',
    district: 'Pérolles',
    npa: '1700',
    canton: 'FR',
    lat: 46.7950,
    lng: 7.1530,
    price: 45,
    priceLabel: '45 CHF / cours',
    rating: 4.9,
    reviewCount: 62,
    image: 'https://picsum.photos/seed/act-009/800/600',
    shortDescription: 'Apprenez le piano avec une pédagogie douce et progressive adaptée aux enfants.',
    description: 'Nos cours de piano pour enfants utilisent une pédagogie active et bienveillante. Dès le premier cours, l\'enfant joue une mélodie simple et ressent la fierté de la création. Nous travaillons lecture de notes, technique, répertoire classique et moderne selon les envies de chaque élève.',
    tags: ['Piano', 'Classique', 'Progressif', 'Individuel'],
    nextDate: '2025-04-18',
    duration: '30min',
    organizer: organizers[2],
    isIndoor: true,
    isFeatured: false,
    isPopular: false,
    isCoupDeCoeur: false,
    availableSlots: 2,
    benefits: ['Patience & persévérance', 'Lecture musicale', 'Créativité', 'Discipline positive'],
    practical: {
      address: '15 boulevard de Pérolles, 1700 Fribourg',
      transport: 'Bus 1, arrêt Pérolles Centre',
      equipment: 'Piano de concert disponible',
      toProvide: 'Méthode de piano (fournie à l\'inscription)',
    },
  },
  {
    id: 'act-010',
    slug: 'sortie-famille-sion',
    name: 'Balade Contée — Sion entre Châteaux',
    category: 'Sorties famille',
    ageMin: 3,
    ageMax: 10,
    ageLabel: '5-7 ans',
    city: 'Sion',
    district: 'Vieille-Ville',
    npa: '1950',
    canton: 'VS',
    lat: 46.2310,
    lng: 7.3580,
    price: 12,
    priceLabel: '12 CHF / enfant, adultes gratuits',
    rating: 4.6,
    reviewCount: 38,
    image: 'https://picsum.photos/seed/act-010/800/600',
    shortDescription: 'Découvrez Sion à travers des histoires et des légendes en famille.',
    description: 'Un conteur vous entraîne à travers les ruelles et les places de Sion pour vous raconter les légendes et les anecdotes de la cité médiévale. Une façon originale et magique de découvrir le patrimoine local en famille. Adaptée aux enfants dès 3 ans, la balade mêle histoire, humour et magie.',
    tags: ['Balade', 'Culturel', 'Famille', 'Conteur'],
    nextDate: '2025-04-20',
    duration: '1h30',
    organizer: organizers[5],
    isIndoor: false,
    isFeatured: false,
    isPopular: false,
    isCoupDeCoeur: false,
    availableSlots: 15,
    benefits: ['Culture locale', 'Imaginaire', 'Lien familial', 'Accessible dès 3 ans'],
    practical: {
      address: 'Place de la Planta, 1950 Sion (face à la mairie)',
      transport: 'Bus 1, arrêt Place de la Planta',
      equipment: 'Aucun',
      toProvide: 'Chaussures confortables',
    },
  },
  {
    id: 'act-011',
    slug: 'atelier-poterie-montreux',
    name: 'Atelier Poterie — Les Mains dans la Terre',
    category: 'Art créatif',
    ageMin: 6,
    ageMax: 14,
    ageLabel: '8-10 ans',
    city: 'Montreux',
    district: 'Vieille-Ville',
    npa: '1820',
    canton: 'VD',
    lat: 46.4350,
    lng: 6.9150,
    price: 34,
    priceLabel: '34 CHF / séance',
    rating: 4.8,
    reviewCount: 44,
    image: 'https://picsum.photos/seed/act-011/800/600',
    shortDescription: 'Initiez-vous à la poterie et repartez avec vos créations cuites et peintes.',
    description: 'La poterie, c\'est une expérience sensorielle unique. Votre enfant apprend à travailler l\'argile, à former des bols, des vases ou des figurines. Après cuisson, il peint et vernit sa création. Un souvenir tangible et une fierté immense. Encadrement par une céramiste professionnelle.',
    tags: ['Poterie', 'Argile', 'Sensoriel', 'Création'],
    nextDate: '2025-04-24',
    duration: '2h',
    organizer: organizers[0],
    isIndoor: true,
    isFeatured: false,
    isPopular: true,
    isCoupDeCoeur: true,
    availableSlots: 5,
    benefits: ['Créativité 3D', 'Motricité fine', 'Patience', 'Objet à ramener'],
    practical: {
      address: '3 rue du Marché, 1820 Montreux',
      transport: 'Bus 201, arrêt Montreux-Marché',
      equipment: 'Argile et outils fournis',
      toProvide: 'Vêtements que vous ne craignez pas de salir',
    },
  },
  {
    id: 'act-012',
    slug: 'judo-enfants-neuchatel',
    name: 'Judo Éveil — Respect & Agilité',
    category: 'Sport',
    ageMin: 3,
    ageMax: 7,
    ageLabel: '2-4 ans',
    city: 'Neuchâtel',
    district: 'Serrières',
    npa: '2000',
    canton: 'NE',
    lat: 46.9980,
    lng: 6.9100,
    price: 25,
    priceLabel: '25 CHF / séance',
    rating: 4.7,
    reviewCount: 71,
    image: 'https://picsum.photos/seed/act-012/800/600',
    shortDescription: 'Initiation au judo dans un cadre bienveillant, axé sur les valeurs et le jeu.',
    description: 'Le judo éveil, c\'est bien plus qu\'un sport. C\'est une école de vie où les enfants apprennent le respect, la chute, l\'équilibre et l\'agilité. Nos moniteurs créent une atmosphère de confiance où chaque enfant progresse selon ses capacités. Les valeurs du judo (respect, entraide, persévérance) sont transmises naturellement.',
    tags: ['Judo', 'Arts martiaux', 'Valeurs', 'Agilité'],
    nextDate: '2025-04-22',
    duration: '1h',
    organizer: organizers[1],
    isIndoor: true,
    isFeatured: false,
    isPopular: false,
    isCoupDeCoeur: false,
    availableSlots: 8,
    benefits: ['Respect & discipline', 'Chute maîtrisée', 'Coordination', 'Confiance en soi'],
    practical: {
      address: 'Salle de sport des Jeunes-Rives, 2000 Neuchâtel',
      transport: 'Bus 101, arrêt Serrières',
      equipment: 'Judogi fourni à la première séance',
      toProvide: 'Rien pour la première séance',
    },
  },
]

export const categories: { name: Category; icon: string; count: number; color: string }[] = [
  { name: 'Sport', icon: '⚽', count: 24, color: '#FF6B52' },
  { name: 'Art créatif', icon: '🎨', count: 18, color: '#EA580C' },
  { name: 'Musique', icon: '🎵', count: 12, color: '#7C3AED' },
  { name: 'Danse', icon: '💃', count: 9, color: '#DB2777' },
  { name: 'Science', icon: '🔬', count: 8, color: '#0284C7' },
  { name: 'Nature', icon: '🌿', count: 11, color: '#65A30D' },
  { name: 'Ateliers', icon: '✂️', count: 15, color: '#D97706' },
  { name: 'Anniversaires', icon: '🎂', count: 7, color: '#E11D48' },
  { name: 'Stages vacances', icon: '🏕️', count: 13, color: '#0891B2' },
  { name: 'Sorties famille', icon: '👨‍👩‍👧', count: 6, color: '#4F46E5' },
]

export const cities = ['Genève', 'Lausanne', 'Fribourg', 'Neuchâtel', 'Sion', 'Montreux']

export type Location = {
  label: string
  type: 'ville' | 'npa' | 'canton'
  filterFn: (a: Activity) => boolean
}

export const locations: Location[] = [
  // Villes
  { label: 'Genève', type: 'ville', filterFn: (a) => a.city === 'Genève' },
  { label: 'Lausanne', type: 'ville', filterFn: (a) => a.city === 'Lausanne' },
  { label: 'Fribourg', type: 'ville', filterFn: (a) => a.city === 'Fribourg' },
  { label: 'Neuchâtel', type: 'ville', filterFn: (a) => a.city === 'Neuchâtel' },
  { label: 'Sion', type: 'ville', filterFn: (a) => a.city === 'Sion' },
  { label: 'Montreux', type: 'ville', filterFn: (a) => a.city === 'Montreux' },
  { label: 'Nyon', type: 'ville', filterFn: (a) => a.city === 'Nyon' },
  { label: 'Yverdon-les-Bains', type: 'ville', filterFn: (a) => a.city === 'Yverdon-les-Bains' },
  { label: 'La Chaux-de-Fonds', type: 'ville', filterFn: (a) => a.city === 'La Chaux-de-Fonds' },
  { label: 'Morges', type: 'ville', filterFn: (a) => a.city === 'Morges' },
  { label: 'Vevey', type: 'ville', filterFn: (a) => a.city === 'Vevey' },
  { label: 'Bienne', type: 'ville', filterFn: (a) => a.city === 'Bienne' },
  { label: 'Delémont', type: 'ville', filterFn: (a) => a.city === 'Delémont' },
  { label: 'Sierre', type: 'ville', filterFn: (a) => a.city === 'Sierre' },
  { label: 'Martigny', type: 'ville', filterFn: (a) => a.city === 'Martigny' },
  // NPA
  { label: '1200 – Genève', type: 'npa', filterFn: (a) => a.canton === 'GE' },
  { label: '1204 – Genève Vieille-Ville', type: 'npa', filterFn: (a) => a.npa === '1204' },
  { label: '1207 – Genève Eaux-Vives', type: 'npa', filterFn: (a) => a.npa === '1207' },
  { label: '1000 – Lausanne', type: 'npa', filterFn: (a) => a.city === 'Lausanne' },
  { label: '1007 – Lausanne Ouchy / Vidy', type: 'npa', filterFn: (a) => a.npa === '1007' },
  { label: '1700 – Fribourg', type: 'npa', filterFn: (a) => a.npa === '1700' },
  { label: '1820 – Montreux', type: 'npa', filterFn: (a) => a.npa === '1820' },
  { label: '1950 – Sion', type: 'npa', filterFn: (a) => a.npa === '1950' },
  { label: '2000 – Neuchâtel', type: 'npa', filterFn: (a) => a.npa === '2000' },
  { label: '1260 – Nyon', type: 'npa', filterFn: (a) => a.city === 'Nyon' },
  { label: '1400 – Yverdon-les-Bains', type: 'npa', filterFn: (a) => a.city === 'Yverdon-les-Bains' },
  { label: '1800 – Vevey', type: 'npa', filterFn: (a) => a.city === 'Vevey' },
  // Cantons
  { label: 'Canton de Genève (GE)', type: 'canton', filterFn: (a) => a.canton === 'GE' },
  { label: 'Canton de Vaud (VD)', type: 'canton', filterFn: (a) => a.canton === 'VD' },
  { label: 'Canton de Fribourg (FR)', type: 'canton', filterFn: (a) => a.canton === 'FR' },
  { label: 'Canton de Neuchâtel (NE)', type: 'canton', filterFn: (a) => a.canton === 'NE' },
  { label: 'Canton du Valais (VS)', type: 'canton', filterFn: (a) => a.canton === 'VS' },
  { label: 'Canton du Jura (JU)', type: 'canton', filterFn: (a) => a.canton === 'JU' },
  { label: 'Canton de Berne (BE)', type: 'canton', filterFn: (a) => a.canton === 'BE' },
]

export const featuredActivities = activities.filter(a => a.isFeatured)
export const popularActivities = activities.filter(a => a.isPopular)
export const coupDeCoeurActivities = activities.filter(a => a.isCoupDeCoeur)
